In [141]:
import pandas as pd
import numpy as np
import matplotlib as plt
import re
from bs4 import BeautifulSoup
import json
import requests
from IPython.display import Image
import os
import urllib.request
import glob
import cv2

In [2]:
# EXAMPLE
url_image = "https://assets.vogue.com/photos/5e5e9a03a173d70008c051d2/master/pass/_FIO0937.jpg"
path = "../inputs/images/test00.jpg"
urllib.request.urlretrieve(url_image, path)

('../inputs/images/test00.jpg', <http.client.HTTPMessage at 0x10e418cd0>)

In [3]:
#Request API function
def requestJSON(url):
    res = requests.get(url)
    if res.status_code != 200:
        print(res.text)
        raise ValueError("Bad Response")
    return res.json()

In [125]:
def extractVogue(designer,collection,urls,names,count=0):
      
    url = f'https://www.vogue.com/fashion-shows/{collection}/{designer}/slideshow/collection/print'

    data = requests.get(url).text
    soup = BeautifulSoup(data, 'html.parser')
    images = soup.select('.slide--image')
    
    for image in images:
        url_name = image['src']
        name = "OK_"+str(count).zfill(6)
        urls.append(url_name)
        names.append(name)
        count+=1
        
        #Extract the pictures
        path_name = '../inputs/images/{}.jpg'.format(name)
        urllib.request.urlretrieve(url_name, path_name)

    #Create dataframe
    df = pd.DataFrame()
    df["urls"]=urls
    df["names"]=names
    df = df.set_index("names")
    df = df.drop_duplicates()
    
    return df,urls,names,count

In [126]:
lst = ['lacoste','miu-miu','louis-vuitton','chanel','altuzarra','hermes']
count = 0
urls = []
names = []
for i in lst:
    url = f'https://www.vogue.com/fashion-shows/fall-2020-ready-to-wear/{i}/slideshow/collection/print'

    data = requests.get(url).text
    soup = BeautifulSoup(data, 'html.parser')
    images = soup.select('.slide--image')

    for ind,image in enumerate(images):
        url_name = image['src']
        name = "OK_"+str(count).zfill(6)
        urls.append(url_name)
        names.append(name)
        count+= 1
        
        #Extract the pictures
        path_name = '../inputs/images/{}.jpg'.format(name)
        urllib.request.urlretrieve(url_name, path_name)

#Create dataframe
df = pd.DataFrame()
df["urls"]=urls
df["names"]=names
df = df.set_index("names")
df = df.drop_duplicates()
df = df.reset_index(drop=True)

print(count)

340

In [127]:
df,urls,names,count = extractVogue("moises-nieto","madrid-spring-2020",urls,names,count)

In [128]:
df

                                                        urls
names
OK_000000  https://assets.vogue.com/photos/5e5e9a3cc66797...
OK_000001  https://assets.vogue.com/photos/5e5e99ef02f19a...
OK_000002  https://assets.vogue.com/photos/5e5e9a61b8b636...
OK_000003  https://assets.vogue.com/photos/5e5e9a1ea173d7...
OK_000004  https://assets.vogue.com/photos/5e5e99f36dd294...
...                                                      ...
OK_000368  https://assets.vogue.com/photos/5d1fb29180c51b...
OK_000369  https://assets.vogue.com/photos/5d1fb2b2212794...
OK_000370  https://assets.vogue.com/photos/5d1fb2a7e7d74e...
OK_000371  https://assets.vogue.com/photos/5d1fb2bd1bce71...
OK_000372  https://assets.vogue.com/photos/5d1fb2b880c51b...

[373 rows x 1 columns]

In [129]:
df,urls,names,count = extractVogue("jacquemus","spring-2020-menswear",urls,names,count)

In [130]:
df,urls,names,count = extractVogue("ludovic-de-saint-sernin","spring-2020-menswear",urls,names,count)

In [131]:
df,urls,names,count = extractVogue("abasi-rosborough","spring-2020-menswear",urls,names,count)

In [132]:
df,urls,names,count = extractVogue("alyx","fall-2020-menswear",urls,names,count)

In [133]:
df,urls,names,count = extractVogue("todd-snyder","spring-2019-menswear",urls,names,count)

In [134]:
df

                                                        urls
names
OK_000000  https://assets.vogue.com/photos/5e5e9a3cc66797...
OK_000001  https://assets.vogue.com/photos/5e5e99ef02f19a...
OK_000002  https://assets.vogue.com/photos/5e5e9a61b8b636...
OK_000003  https://assets.vogue.com/photos/5e5e9a1ea173d7...
OK_000004  https://assets.vogue.com/photos/5e5e99f36dd294...
...                                                      ...
OK_000569  https://assets.vogue.com/photos/5b46b5d25002ba...
OK_000570  https://assets.vogue.com/photos/5b46b5d4bc8685...
OK_000571  https://assets.vogue.com/photos/5b46b5d6bc8685...
OK_000572  https://assets.vogue.com/photos/5b46b5d85002ba...
OK_000573  https://assets.vogue.com/photos/5b46b5d9cfb35f...

[574 rows x 1 columns]

In [135]:
print(count)

574

In [136]:
df,urls,names,count = extractVogue("berluti","spring-2017-menswear",urls,names,count)

In [137]:
df

                                                        urls
names
OK_000000  https://assets.vogue.com/photos/5e5e9a3cc66797...
OK_000001  https://assets.vogue.com/photos/5e5e99ef02f19a...
OK_000002  https://assets.vogue.com/photos/5e5e9a61b8b636...
OK_000003  https://assets.vogue.com/photos/5e5e9a1ea173d7...
OK_000004  https://assets.vogue.com/photos/5e5e99f36dd294...
...                                                      ...
OK_000590  https://assets.vogue.com/photos/576eb6655124fe...
OK_000591  https://assets.vogue.com/photos/576eb664127111...
OK_000592  https://assets.vogue.com/photos/576eb668127111...
OK_000593  https://assets.vogue.com/photos/576eb668d7b4ae...
OK_000594  https://assets.vogue.com/photos/576eb66b5124fe...

[595 rows x 1 columns]

In [138]:
count

595

In [139]:
df

                                                        urls
names
OK_000000  https://assets.vogue.com/photos/5e5e9a3cc66797...
OK_000001  https://assets.vogue.com/photos/5e5e99ef02f19a...
OK_000002  https://assets.vogue.com/photos/5e5e9a61b8b636...
OK_000003  https://assets.vogue.com/photos/5e5e9a1ea173d7...
OK_000004  https://assets.vogue.com/photos/5e5e99f36dd294...
...                                                      ...
OK_000590  https://assets.vogue.com/photos/576eb6655124fe...
OK_000591  https://assets.vogue.com/photos/576eb664127111...
OK_000592  https://assets.vogue.com/photos/576eb668127111...
OK_000593  https://assets.vogue.com/photos/576eb668d7b4ae...
OK_000594  https://assets.vogue.com/photos/576eb66b5124fe...

[595 rows x 1 columns]

In [142]:
KO_list = glob.glob("../inputs/images/People_No/*.jpg")

In [155]:
dfno = pd.DataFrame()
dfno["urls"]= KO_list
dfno = dfno.reset_index()
dfno = dfno.rename(columns={"index":"order"})
dfno["names"] = dfno.order.apply(lambda x: "KO_"+str(x).zfill(6))
dfno = dfno.drop(columns=["order"])
dfno["GT"]= dfno.names.apply(lambda x: "KO")
dfno = dfno.set_index("names")
dfno

                                           urls  GT
names
KO_000000  ../inputs/People_No/000000568981.jpg  KO
KO_000001  ../inputs/People_No/000000570664.jpg  KO
KO_000002  ../inputs/People_No/000000577862.jpg  KO
KO_000003  ../inputs/People_No/000000572517.jpg  KO
KO_000004  ../inputs/People_No/000000521601.jpg  KO
...                                         ...  ..
KO_000496  ../inputs/People_No/000000569700.jpg  KO
KO_000497  ../inputs/People_No/000000523782.jpg  KO
KO_000498  ../inputs/People_No/000000545407.jpg  KO
KO_000499  ../inputs/People_No/000000578792.jpg  KO
KO_000500  ../inputs/People_No/000000523033.jpg  KO

[501 rows x 2 columns]

In [160]:
df = df.reset_index(drop=True)

In [163]:
df = df.drop(columns=["index"])

In [164]:
df

         names                                               urls
0    OK_000000  https://assets.vogue.com/photos/5e5e9a3cc66797...
1    OK_000001  https://assets.vogue.com/photos/5e5e99ef02f19a...
2    OK_000002  https://assets.vogue.com/photos/5e5e9a61b8b636...
3    OK_000003  https://assets.vogue.com/photos/5e5e9a1ea173d7...
4    OK_000004  https://assets.vogue.com/photos/5e5e99f36dd294...
..         ...                                                ...
590  OK_000590  https://assets.vogue.com/photos/576eb6655124fe...
591  OK_000591  https://assets.vogue.com/photos/576eb664127111...
592  OK_000592  https://assets.vogue.com/photos/576eb668127111...
593  OK_000593  https://assets.vogue.com/photos/576eb668d7b4ae...
594  OK_000594  https://assets.vogue.com/photos/576eb66b5124fe...

[595 rows x 2 columns]

In [165]:
df["GT"]= df.names.apply(lambda x: "OK")

In [168]:
df = df.set_index("names")
df

                                                        urls  GT
names
OK_000000  https://assets.vogue.com/photos/5e5e9a3cc66797...  OK
OK_000001  https://assets.vogue.com/photos/5e5e99ef02f19a...  OK
OK_000002  https://assets.vogue.com/photos/5e5e9a61b8b636...  OK
OK_000003  https://assets.vogue.com/photos/5e5e9a1ea173d7...  OK
OK_000004  https://assets.vogue.com/photos/5e5e99f36dd294...  OK
...                                                      ...  ..
OK_000590  https://assets.vogue.com/photos/576eb6655124fe...  OK
OK_000591  https://assets.vogue.com/photos/576eb664127111...  OK
OK_000592  https://assets.vogue.com/photos/576eb668127111...  OK
OK_000593  https://assets.vogue.com/photos/576eb668d7b4ae...  OK
OK_000594  https://assets.vogue.com/photos/576eb66b5124fe...  OK

[595 rows x 2 columns]

In [173]:
OK_list = glob.glob("../inputs/People_Yes_resized_640/*.jpg")

In [176]:
OK_list.sort()

In [181]:
df["path"] = OK_list

In [183]:
dfno["path"]=dfno.urls.apply(lambda x: x)

In [185]:
dfno["urls"]="COCO_Dataset"

In [186]:
dfno

                   urls  GT                                  path
names
KO_000000  COCO_Dataset  KO  ../inputs/People_No/000000568981.jpg
KO_000001  COCO_Dataset  KO  ../inputs/People_No/000000570664.jpg
KO_000002  COCO_Dataset  KO  ../inputs/People_No/000000577862.jpg
KO_000003  COCO_Dataset  KO  ../inputs/People_No/000000572517.jpg
KO_000004  COCO_Dataset  KO  ../inputs/People_No/000000521601.jpg
...                 ...  ..                                   ...
KO_000496  COCO_Dataset  KO  ../inputs/People_No/000000569700.jpg
KO_000497  COCO_Dataset  KO  ../inputs/People_No/000000523782.jpg
KO_000498  COCO_Dataset  KO  ../inputs/People_No/000000545407.jpg
KO_000499  COCO_Dataset  KO  ../inputs/People_No/000000578792.jpg
KO_000500  COCO_Dataset  KO  ../inputs/People_No/000000523033.jpg

[501 rows x 3 columns]

In [188]:
col_ord = ["urls","path","GT"]
dfno = dfno[col_ord]
df = df[col_ord]

,urls,path,GT
names,,,
OK_000000,https://assets.vogue.com/photos/5e5e9a3cc66797...,../inputs/People_Yes_resized_640/OK_000000.jpg,OK
OK_000001,https://assets.vogue.com/photos/5e5e99ef02f19a...,../inputs/People_Yes_resized_640/OK_000001.jpg,OK
OK_000002,https://assets.vogue.com/photos/5e5e9a61b8b636...,../inputs/People_Yes_resized_640/OK_000002.jpg,OK
OK_000003,https://assets.vogue.com/photos/5e5e9a1ea173d7...,../inputs/People_Yes_resized_640/OK_000003.jpg,OK
OK_000004,https://assets.vogue.com/photos/5e5e99f36dd294...,../inputs/People_Yes_resized_640/OK_000004.jpg,OK
...,...,...,...
OK_000590,https://assets.vogue.com/photos/576eb6655124fe...,../inputs/People_Yes_resized_640/OK_000590.jpg,OK
OK_000591,https://assets.vogue.com/photos/576eb664127111...,../inputs/People_Yes_resized_640/OK_000591.jpg,OK
OK_000592,https://assets.vogue.com/photos/576eb668127111...,../inputs/People_Yes_resized_640/OK_000592.jpg,OK
OK_000593,https://assets.vogue.com/photos/576eb668d7b4ae...,../inputs/People_Yes_resized_640/OK_000593.jpg,OK
OK_000594,https://assets.vogue.com/photos/576eb66b5124fe...,../inputs/People_Yes_resized_640/OK_000594.jpg,OK

In [190]:
df_final = pd.concat([df,dfno])

In [191]:
df_final

,urls,path,GT
names,,,
OK_000000,https://assets.vogue.com/photos/5e5e9a3cc66797...,../inputs/People_Yes_resized_640/OK_000000.jpg,OK
OK_000001,https://assets.vogue.com/photos/5e5e99ef02f19a...,../inputs/People_Yes_resized_640/OK_000001.jpg,OK
OK_000002,https://assets.vogue.com/photos/5e5e9a61b8b636...,../inputs/People_Yes_resized_640/OK_000002.jpg,OK
OK_000003,https://assets.vogue.com/photos/5e5e9a1ea173d7...,../inputs/People_Yes_resized_640/OK_000003.jpg,OK
OK_000004,https://assets.vogue.com/photos/5e5e99f36dd294...,../inputs/People_Yes_resized_640/OK_000004.jpg,OK
...,...,...,...
KO_000496,COCO_Dataset,../inputs/People_No/000000569700.jpg,KO
KO_000497,COCO_Dataset,../inputs/People_No/000000523782.jpg,KO
KO_000498,COCO_Dataset,../inputs/People_No/000000545407.jpg,KO
KO_000499,COCO_Dataset,../inputs/People_No/000000578792.jpg,KO
KO_000500,COCO_Dataset,../inputs/People_No/000000523033.jpg,KO

In [194]:
df_final.to_csv("../inputs/datasets/body_reco.csv")